#include "src/args.h"
#include "src/dictionary.h"
#include "src/matrix.h"
#include "src/utils.h"
#include "src/vector.h"
#include "src/model.h"

#include "src/args.cc"
#include "src/dictionary.cc"
#include "src/matrix.cc"
#include "src/vector.cc"
#include "src/model.cc"
#include "src/utils.cc"
#include "src/fasttext.cc"
#include "src/fasttext_wrapper.cc"
